### ISSUE TITLE
Installed npm oauth package cant found

### ISSUE THREAD

**Issue by ajborn** [zeit/now-desktop#460]
I get this error when deploying a nodejs project with the oauth npm package.

Using the same commands the project successfully builds.

For some reason the package is not being installed or installed package cant be read from, from what I understand.

```
03/22 07:19 PM (11m)
npm install
03/22 07:19 PM (11m)
⧗ Installing 9 main dependencies…
03/22 07:19 PM (11m)
✓ Using "package-lock.json"
03/22 07:19 PM (11m)
✓ Installed 164 modules [2s]
03/22 07:19 PM (11m)
npm run build
03/22 07:19 PM (11m)

> austins-profile-server@0.0.1 build /home/nowuser/src
> node server.js
03/22 07:19 PM (11m)
module.js:549
    throw err;

Error: Cannot find module 'OAuth'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nowuser/src/server.js:9:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
03/22 07:19 PM (11m)
npm ERR! code ELIFECYCLE
03/22 07:19 PM (11m)
npm ERR! errno 1
03/22 07:19 PM (11m)
npm ERR! Exit status 1
03/22 07:19 PM (11m)
npm ERR! Failed at the austins-profile-server@0.0.1 build script.
03/22 07:19 PM (11m)
npm ERR! 
03/22 07:19 PM (11m)
npm ERR! austins-profile-server@0.0.1 build: `node server.js`
03/22 07:19 PM (11m)
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
03/22 07:19 PM (11m)

npm ERR! A complete log of this run can be found in:
03/22 07:19 PM (11m)
npm ERR!     /home/nowuser/.npm/_logs/2018-03-23T02_19_25_874Z-debug.log
```

**Comment by ajborn** [comment]
This is the line of code that is called when the build breaks `const oAuth = require('OAuth');`

**Comment by leo** [comment]
Hey! 👋 

This error is most likely appearing because you wrote `OAuth` instead of the correct package name. All packages names are lowercase... 😊
