### ISSUE TITLE
Show modal for first run error

### ISSUE THREAD

**Issue by leo** [zeit/now-desktop#507]
Often times, we get this error. However, the user doesn't see it. Can we show a modal to ask the user to fix his permissions?

@joecohens Do you have any cool idea on how to handle this? 🤔 

The package basically ensures we do certain things only on the first run (like showing the tutorial).

```
Error: EACCES: permission denied, open '/Users/xxxxxxxxx/.config/configstore/first-run_now-desktop.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:510:29)
    at Configstore.get (/Applications/Now.app/Contents/Resources/app.asar/node_modules/first-run/node_modules/configstore/index.js:35:26)
    at new Configstore (/Applications/Now.app/Contents/Resources/app.asar/node_modules/first-run/node_modules/configstore/index.js:28:45)
    at getConf (/Applications/Now.app/Contents/Resources/app.asar/node_modules/first-run/index.js:20:9)
    at firstRun (/Applications/Now.app/Contents/Resources/app.asar/node_modules/first-run/index.js:25:13)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/app.asar/main/index.js:66:15)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/app.asar/main/index.js:244:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/electron.asar/browser/init.js:186:8)
```

**Comment by morajabi** [comment]
@leo I got this error for There too. first-run uses [a different config store](https://github.com/sindresorhus/first-run/blob/master/index.js#L3) option than electron-store, that's the reason one fails and one doesn't.

I think we should write a version of first-run based on electron-store. That'd also reduce package size and startup time.

**Comment by joecohens** [comment]
I'll think about something cool :) 

@morajabi Thanks for the info I'll dig more, still I think electron-store writes the config to a dir so if you don't have permission to write it will still silently fail .

**Comment by morajabi** [comment]
@joecohens Nice :) Yes, It does save to a dir. 

But the `first-run` saves the config in `~/.config` folder which is normal in Linux, but not at all in macOS which is causing the problem. 

Electron-store, however, saves the data in the best-suited path for the OS (from [electron/api/app#appgetpathname](https://electronjs.org/docs/api/app#appgetpathname)):
- `%APPDATA%` on Windows
- `$XDG_CONFIG_HOME` or `~/.config` on Linux
- `~/Library/Application` Support on macOS

Electron store docs:
> Electron doesn't have a built-in way to persist user preferences and other data. This module handles that for you, so you can focus on building your app. The data is saved in a JSON file in [app.getPath('userData')](https://electronjs.org/docs/api/app#appgetpathname).

I hope it helps :)

**Comment by joecohens** [comment]
Ok so I've tested `electron-config` and it looks like it's working fine :) what do you guys think? https://github.com/zeit/now-desktop/pull/512

It's funny, I've found that many other apps use `first-run` like Kap and There by looking at the `.config/configstore` folder.

**Comment by morajabi** [comment]
`first-run` hasn't been updated in a while, probably if we swap the `configstore` package for `electron-store` so many people will benefit!
