### ISSUE TITLE
TypeError: pkg.includes is not a function

### ISSUE THREAD

**Issue by lvnilesh** [zeit/now-desktop#582]
```
Uncaught Exception:
TypeError: pkg.includes is not a function
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/app.asar/main/index.js:26:22)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/app.asar/main/index.js:303:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/electron.asar/browser/init.js:189:8)
    at Object.<anonymous> (/Applications/Now.app/Contents/Resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)

```

**Comment by pouyio** [comment]
same here, Macos Mojave 10.14.2

**Comment by KevSlashNull** [comment]
Experiencing the same issue here. MacOS High Sierra 10.13.6.

![image](https://user-images.githubusercontent.com/28510368/50116836-90ffd980-024b-11e9-87a7-70faceaeaefe.png)

**Comment by pouyio** [comment]
Got a nice email from zeit this morning. Reinstalling fixed it and I didn't have to log in again.

**Comment by MAPESO** [comment]
@lvnilesh Hi 👋  can you tell me the steps to reproduce this error :]

**Comment by MAPESO** [comment]
In case this problem is already solved, it would be convenient to close this topic ^-^

**Comment by juliangruber** [comment]
Closing as it looks like this has been fixed in recent versions of Now Desktop

**Comment by Irrelon** [comment]
Just downloaded latest version but same issue!

**Comment by Irrelon** [comment]
Found the problem. Had to go into activity monitor and force quit now process. After that, the new version was able to load.
