### ISSUE TITLE
Please document Linux instructions and/or publish Deb/snap

### ISSUE THREAD

**Issue by ajbogh** [zeit/now-desktop#587]
**Instructions for Linux users:**

1) Clone now-desktop

```bash
git clone git@github.com:zeit/now-desktop.git
cd now-desktop
```

2) Install dependencies (make sure to [fix permissions using these instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally))

```
npm install -g yarn
npm install
```

3) Run the build script

```
npm run build
```

4) find the linux-unpacked folder

```
cd ./dist/linux-unpacked
```

5) Run the `now-desktop` file

```
./now-desktop
```

A new triangular icon will show in the top panel. Click it to see the menus. Click Preferences and then enable `Launch at Login`.

**Comment by MAPESO** [comment]
@leo  @rauchg  It would be a good idea to have a special section to install `now-desktop` for Linux users. Since in that operative system it is necessary to realize more additional steps to install an application in comparison to `Windows` or `macOS`.  I am available to write the document indicating the steps :]

**Comment by juliangruber** [comment]
Related to https://github.com/zeit/now-desktop/issues/549

**Comment by hafidium** [comment]
> 1. Run the `now-desktop` file
> 
> ```
> ./now-desktop
> ```

I keep getting an error :
> ```
> TypeError: systemPreferences.subscribeNotification is not a function
> at WebContents.<anonymous> (/home/hafidzpermana/Documents/now-desktop/dist/linux- unpacked/resources/app.asar/main/ipc.js:94:23)
> at WebContents.emit (events.js:199:15)
> at WebContents.EventEmitter.emit (domain.js:469:20)
> at WebContents.emitter.emit (/home/hafidzpermana/Documents/now-desktop/dist/linux-unpacked/resources/app.asar/node_modules/@sentry/electron/src/main/integrations/electron.ts:73:14)
> at WebContents.topLevelDomainCallback (domain.js:124:23)
> ```
@ajbogh

**Comment by ajbogh** [comment]
@hafidium the instructions I've documented are specific to the version available at the time of my comment. If there are new bugs then you may see new issues in your installation or running of the application. You should create a new issue to the now-desktop team regarding that new problem.
